updated github action

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -40,90 +40,90 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           
-  CI-Build:
-    needs: CI-Code
-    runs-on: ubuntu-20.04
+  # CI-Build:
+  #   needs: CI-Code
+  #   runs-on: ubuntu-20.04
       
-    steps:   
+  #   steps:   
    
-      - name: Checkout code
-        uses: actions/checkout@v2
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
         
-      - name: Setup pipeline enforcer
-        uses: aquasecurity/pipeline-enforcer-action@main
-        with:
-          aqua-key: ${{ secrets.AQUA_KEY }}
-          aqua-secret: ${{ secrets.AQUA_SECRET }}
+  #     - name: Setup pipeline enforcer
+  #       uses: aquasecurity/pipeline-enforcer-action@main
+  #       with:
+  #         aqua-key: ${{ secrets.AQUA_KEY }}
+  #         aqua-secret: ${{ secrets.AQUA_SECRET }}
   
-      - name: Build application
-        run: echo Application has been succesfully built 
+  #     - name: Build application
+  #       run: echo Application has been succesfully built 
         
-      #https://github.com/marketplace/actions/build-and-push-docker-images
-      #https://docs.docker.com/build/ci/github-actions/test-before-push/
-      #- name: Set up Docker Buildx
-      #  uses: docker/setup-buildx-action@v2
-      #- name: Build and push the Docker image
-      #  uses: docker/build-push-action@v4
-      #  with:
-      #    tags: |
-      #      $DOCKER_REPOSITORY/$IMAGE_NAME:latest
-      #      $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
-      #    push: true
-      #    #cache-from: type=gha
-      #    #cache-to: type=gha,mode=max
+  #     #https://github.com/marketplace/actions/build-and-push-docker-images
+  #     #https://docs.docker.com/build/ci/github-actions/test-before-push/
+  #     #- name: Set up Docker Buildx
+  #     #  uses: docker/setup-buildx-action@v2
+  #     #- name: Build and push the Docker image
+  #     #  uses: docker/build-push-action@v4
+  #     #  with:
+  #     #    tags: |
+  #     #      $DOCKER_REPOSITORY/$IMAGE_NAME:latest
+  #     #      $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
+  #     #    push: true
+  #     #    #cache-from: type=gha
+  #     #    #cache-to: type=gha,mode=max
           
           
-      - name: Build image container
-        run: |
-          sudo docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
+  #     - name: Build image container
+  #       run: |
+  #         sudo docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
         
-      - name: Login to Aqua Registry
-        uses: docker/login-action@v1
-        with:
-          registry: registry.aquasec.com
-          username: ${{ secrets.AQUA_REGISTRY_USERNAME }}
-          password: ${{ secrets.AQUA_REGISTRY_PASS }}
+  #     - name: Login to Aqua Registry
+  #       uses: docker/login-action@v1
+  #       with:
+  #         registry: registry.aquasec.com
+  #         username: ${{ secrets.AQUA_REGISTRY_USERNAME }}
+  #         password: ${{ secrets.AQUA_REGISTRY_PASS }}
           
-      - name: Scanning container image
-        run: |
-          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --register --registry "CI/CD_andres_images" --host ${{ secrets.AQUA_HOST }} --local $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG --token ${{ secrets.AQUA_TOKEN }} --layer-vulnerabilities --no-verify --html > .github/workflows/scan-output.html
-      # -e BUILD_JOB_NAME=$CI_JOB_NAME -e BUILD_URL=$CI_JOB_URL -e BUILD_NUMBER=$CI_JOB_ID
+  #     - name: Scanning container image
+  #       run: |
+  #         docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --register --registry "CI/CD_andres_images" --host ${{ secrets.AQUA_HOST }} --local $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG --token ${{ secrets.AQUA_TOKEN }} --layer-vulnerabilities --no-verify --html > .github/workflows/scan-output.html
+  #     # -e BUILD_JOB_NAME=$CI_JOB_NAME -e BUILD_URL=$CI_JOB_URL -e BUILD_NUMBER=$CI_JOB_ID
         
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
           
-      - name: Docker Login & Push
-        run: |
-          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG 
-          docker tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG $DOCKER_REPOSITORY/$IMAGE_NAME:latest
-          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:latest 
-        #docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
+  #     - name: Docker Login & Push
+  #       run: |
+  #         echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+  #         docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG 
+  #         docker tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG $DOCKER_REPOSITORY/$IMAGE_NAME:latest
+  #         docker push $DOCKER_REPOSITORY/$IMAGE_NAME:latest 
+  #       #docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
-      - name: SBOM Generation
-        run: |
-          export BILLY_SERVER=https://billy.codesec.aquasec.com
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum ; then
-          echo "install.sh checksum failed"
-          exit 1
-          fi
-          BINDIR="." sh install.sh
-          rm install.sh install.sh.checksum
-          ./billy generate \
-            --access-token "${{ github.token }}" \
-            --aqua-key "${{ secrets.AQUA_KEY }}" \
-            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            --artifact-path "$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"
+  #     - name: SBOM Generation
+  #       run: |
+  #         export BILLY_SERVER=https://billy.codesec.aquasec.com
+  #         curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+  #         curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+  #         if ! cat install.sh.checksum | sha256sum ; then
+  #         echo "install.sh checksum failed"
+  #         exit 1
+  #         fi
+  #         BINDIR="." sh install.sh
+  #         rm install.sh install.sh.checksum
+  #         ./billy generate \
+  #           --access-token "${{ github.token }}" \
+  #           --aqua-key "${{ secrets.AQUA_KEY }}" \
+  #           --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+  #           --artifact-path "$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"
 
-            # The docker image name:tag of the newly built image
-            # --artifact-path "my-image-name:${{ env.tag-version }}" 
-            # OR the path to the root folder of your project. I.e my-repo/my-app 
-            ## --artifact-path "${{env.MY_APP_ROOT}}"
+  #           # The docker image name:tag of the newly built image
+  #           # --artifact-path "my-image-name:${{ env.tag-version }}" 
+  #           # OR the path to the root folder of your project. I.e my-repo/my-app 
+  #           ## --artifact-path "${{env.MY_APP_ROOT}}"
             
 #   CD-Deploy_to_dev:
 #     #if: github.ref == 'refs/heads/development'
